### ISSUE TITLE
10.4 Release Name

### ISSUE THREAD

**Issue by dmx78** [ideasawakened/DelphiKB#27]
The new 10.4 release name haven't been release yet, are you sure it will be Sydney? Currently the beta name is Denali

**Comment by darianmiller** [comment]
Fairly confident.  While the name hasn't been officially released, they used the reference **10.4 Sydney** in a recent marketing email regarding a pre-release sales offer.   It's the first I've seen other than "Denali" name for 10.4 Beta.  I imagine there's a small chance that their marketing email could be wrong about the name, but I assume they put it out there just to create a little bit of a pre-release buzz as the estimated ship date is slipping.  (Or perhaps the marketing guys simply screwed up and released the name early.) 

![image](https://user-images.githubusercontent.com/3165264/81570975-ee2b8c00-9366-11ea-9bda-6f22bb948706.png)

**Comment by dmx78** [comment]
Yes, i just receive it today, maybe you got it first, it just that i
assuming Denali is in Alaska, so it should be Alaska instead of Sydney :D

It's okey, close the case, and just update it when it is release

Cheers

**Comment by darianmiller** [comment]
I agree it's a little off - but with Delphi 10.1 Berlin, the beta name was "Big Ben" (London reference) and for Delphi 10.0 Seattle, the beta name was "Aitana" a mountain in Spain.

On the flip side, the latest two were matches:  Godzilla / Tokyo and then Carnival / Rio
